name: Calc App CI Pipeline

on:
  workflow_run:
    workflows: ["Calc App Unit Tests"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Build Docker Images
        run: |
          (cd backend && docker build -t calc-be:latest .)
          (cd frontend && npm ci && npm run build)
          (cd frontend && docker build -t calc-fe:latest .)
      - name: Health Check for the Built Images
        run: |
          docker run -d -p 8000:3031 --name test-be calc-be:latest
          docker run -d -p 9000:3000 --name test-fe calc-fe:latest
          sleep 5
          curl --fail "http://localhost:8000/healthcheck" || exit 1
          curl --fail "http://localhost:9000" || exit 1
      - name: Stop and Remove the Test Containers
        if: always()
        run: |
          docker stop test-be
          docker stop test-fe
          docker rm test-be
          docker rm test-fe
